import cv2
img = cv2.imread('Lab1/haruhi.jpg')
cv2.namedWindow('5 seconds', flags=cv2.WINDOW_AUTOSIZE)
cv2.imshow('5 seconds', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()
img_gray = cv2.imread('Lab1/haruhi.jpg', flags=cv2.IMREAD_GRAYSCALE)
cv2.namedWindow('7 seconds', flags=cv2.WINDOW_AUTOSIZE)
cv2.imshow('7 seconds', img_gray)
cv2.waitKey(7000)
cv2.destroyAllWindows()
dim = (int(img.shape[1] / 2), int(img.shape[0] / 2))
img = cv2.resize(img, dim, interpolation=cv2.INTER_NEAREST)
cv2.namedWindow('9 seconds', flags=cv2.WINDOW_AUTOSIZE)
cv2.imshow('9 seconds', img)
cv2.waitKey(9000)
cv2.destroyAllWindows()
dim = (int(img_gray.shape[1] / 4), int(img_gray.shape[0] / 4))
img_gray = cv2.resize(img_gray, dim, interpolation=cv2.INTER_NEAREST)
cv2.namedWindow('11 seconds', flags=cv2.WINDOW_AUTOSIZE)
cv2.imshow('11 seconds', img_gray)
cv2.waitKey(11000)
cv2.destroyAllWindows()
img = cv2.imread('Lab1/haruhi.jpg', flags=cv2.IMREAD_COLOR)
b, g, r = cv2.split(img)
img2 = cv2.merge((b, r, g))
cv2.namedWindow('4 seconds', flags=cv2.WINDOW_AUTOSIZE)
cv2.imshow('4 seconds', img2)
cv2.waitKey(4000)
cv2.imshow('4 seconds', img)
while True:
    key = cv2.waitKey(0)
    if key == 27 or key == -1:
        break
